### ISSUE TITLE
Regression: Inspection "Class has too big memory footprint" ignored suffixes are not editable

### ISSUE THREAD

**Issue by Firestar99** [stokito/IdeaJol#33]
The Inspection "Class has too big memory footprint" has a List of ignored suffixes which can no longer be removed or new ones added. The +/- buttons don't do anything, no error displayed. Probably broke with the latest update, I remember using this feature a month ago or so successfully.

IntelliJ IDEA 2021.1.2 (Ultimate Edition)
Build #IU-211.7442.40, built on June 1, 2021
Runtime version: 11.0.11+9-b1341.57 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Linux 5.11.0-18-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: documentation.show.toolbar=true, external.system.auto.import.disabled=true
Non-Bundled Plugins: GLSL (1.19), com.intellij.nativeDebug (211.7442.9), mobi.hsz.idea.gitignore (4.1.0), org.toml.lang (0.2.147.3871-211), ASM Bytecode Viewer (7.2), JOL (1.9.1), jclasslib (5.7), Pythonid (211.7442.45), org.rust.lang (0.4.147.3871-211)
Kotlin: 211-1.4.32-release-IJ7442.2
Current Desktop: KDE

**Comment by stokito** [comment]
thank you for the report
