### ISSUE TITLE
Kotlin support works, but not as described

### ISSUE THREAD

**Issue by OliverO2** [stokito/IdeaJol#34]
The _General Usage Instructions_ state:

> Set a cursor into a class name and then press Code / Show Object Layout and you'll see a right panel with layout info.

This does not work with a Kotlin class. When placing the cursor into a class name, the menu _Code / Show Object Layout_ is greyed out.

This works:
1. Place the cursor into a class name.
2. Select _Navigate / Type Hierarchy_ (shortcut: `Ctrl`+`H`).
3. Select _Code / Show Object Layout_.

**Comment by stokito** [comment]
Thank you for the report, I fixed and in two days the release will be available.

**Comment by OliverO2** [comment]
Thank you so much! That was amazingly fast!

**Comment by stokito** [comment]
@OliverO2 just released, thanks for a quick review from JetBrains. Please tell me if something not works with Kotlin because I don't use it and it's support is experimental
