### ISSUE TITLE
Idea JOL broken in 2023.2

### ISSUE THREAD

**Issue by Desoroxxx** [stokito/IdeaJol#42]
https://gist.github.com/Desoroxxx/e9e0c9dc38f3edc84a7f3e9290ffcad9

This happens since I updated to IntelliJ IDEA 2023.2, the plugin does not work in this version.

**Comment by stokito** [comment]
@Desoroxxx thank you for the reporting. It looks like the #38 
Please try to update the plugin. I just removed the Copy icon so any similar issue won't occur in future

**Comment by Desoroxxx** [comment]
I just realized that I cannot update the plugin
![image](https://github.com/stokito/IdeaJol/assets/82710983/49806a99-799d-4c8b-a348-194aa59ef268)
Older versions (1.10.0) lacked upper IntelliJ Idea version which is why it is able to be downloaded on 2023.2

**Comment by Desoroxxx** [comment]
Any news on this?
2023.2 is out in stable now

**Comment by stokito** [comment]
The update was published
https://plugins.jetbrains.com/plugin/10953-jol-java-object-layout/versions/stable/371608
